#!/bin/bash

for f in prefetching2.v?.c;
do
    version=$( echo $f | cut -d'.' -f2 | cut -d'v' -f2)
    echo "compiling prefetching2.vall.c -> " prefetching2.v$version
    if [[ "$version" > 0 ]];
    then
	gcc -std=c11 -DUSE_PAPI -I/${PAPI_DIR}/include -o prefetching2.v$version prefetching2.vall.c -DPREFETCH=$version -L/${PAPI_DIR}/lib -lpapi -lm
	gcc -std=c11 -DUSE_PAPI -I/${PAPI_DIR}/include -O3 -march=native -o prefetching2.v$version.O3n prefetching2.vall.c -DPREFETCH=$version -L/${PAPI_DIR}/lib -lpapi -lm
    else
	gcc -std=c11 -DUSE_PAPI -I/${PAPI_DIR}/include -o prefetching2.v0 prefetching2.v0.c -L/${PAPI_DIR}/lib -lpapi -lm
	gcc -std=c11 -DUSE_PAPI -I/${PAPI_DIR}/include -O3 -march=native -o prefetching2.v0.O3n prefetching2.v0.c -L/${PAPI_DIR}/lib -lpapi -lm
    fi
done
